### PR TITLE
add a property fmt.goal that is 'format' by default for users and is …

### PR DESCRIPTION
**Pull request by tomnelson**
…set to 'check' on the travis-ci builder

 Changes to be committed:
	modified:   .travis.yml
	modified:   pom.xml

### CODE REVIEW

**Comment by jbduncan** [comment]
Hmm, it's unclear to me if this is better than simply changing the `check` to `format`. Would not a user have to always supply an `-Dfmt.goal=...` argument this way?

**Comment by jbduncan** [comment]
Or have I missed something?

**Comment by jbduncan** [comment]
Oh, just remembered that simply changing `check` for `format` would be worse, as it would cause Travis CI to format code instead of validating it. My bad! :P

**Comment by jbduncan** [comment]
If we cannot set a default argument for `-Dfmt.goal=...` i.e. `format`, what other options would we have here?

**Comment by tomnelson** [comment]
line 83 of the pom adds this property
<fmt.goal>format</fmt.goal>
so there is always a default value for the goal

**Comment by jbduncan** [comment]
Oh, yep, that makes obvious sense to me, now that you mention it. Thanks for clarifying things in my mind!

**Comment by jbduncan** [comment]
In that case, this PR LGTM. :+1:

**Comment by tomnelson** [comment]
For purposes of documentation
1. The code in the repo is in a formatted state
2. User checks out code
3. User makes changes (that may be unformatted)
4. User runs mvn clean install to make sure things work (the user's changes
are formatted)
5. User commits code and pushes branch
6. Travis-CI (is configured to) run maven with fmt.goal=check so it only
checks the formatting
7. Profit!

**Comment by jbduncan** [comment]
> 4. User runs mvn clean install to make sure things work (the user's changes
are formatted)

Or, in our case, `mvn` is actually enough, since the pom.xml contains a default goal of `clean verify`, which does the same thing for our intents and purposes. :)

**Comment by jbduncan** [comment]
Actually, sorry for not noticing earlier, but it occurs to me that the `CONTRIBUTING.md` needs to be changed as well, since users will no longer need to run `mvn fmt:format` separately to format code.

Would you mind changing the CONTRIBUTING.md as well with up-to-date instructions?

If you wouldn't mind, then I'd suggest removing the 2nd paragraph about google-java-format and changing the 4th paragraph so it says the following:

> Please make sure your code compiles by running `mvn` which will build the software, **format the code base with google-java-format,** run the tests, and check that the code passes other checks. All pull requests will be validated by Travis CI in any case and typically must pass before being merged.

**Pull request closed without merging**
