### PR TITLE
Add jitpack gradle example...

### PR DESCRIPTION
**Pull request by rgwood-github2018dec31**

### CODE REVIEW

**Comment by jrtom** [comment]
We'd be happy to accept this PR, but we need you to sign the CLA in order for us to do so; otherwise I'll close it.

**Comment by rgwood-github2018dec31** [comment]
I have just signed the agreement but it hasn't updated. Maybe there's some delay?

**Comment by rgwood-github2018dec31** [comment]
image

**Comment by jrtom** [comment]
Looks like it came through.  Thanks!

**Pull request merged**
