### PR TITLE
#230 - corrected repaint for demo

### PR DESCRIPTION
**Pull request by wumpz**

### CODE REVIEW

**Comment by jrtom** [comment]
What behavioral change do you see with this commit?  It would help to understand what problem you're solving.  :)

**Comment by jrtom** [comment]
Sorry, you did specify (in the PR title) which problem this was solving.  It helps to specify that in the commit text, because that way the issue will get updated; I don't think that the PR titles make that connection.

**Comment by jrtom** [comment]
(Apparently the PR titles do (now?) make that connection, so never mind that either.  I'll just need to get used to looking in the title.)

**Comment by wumpz** [comment]
Sorry. That is my common creation of PRs. So I will reference it I. The comments as well.

**Pull request merged**
