### PR TITLE
Add in a deployment script for snapshots

### PR DESCRIPTION
**Pull request by cgruber**
Add in a deployment script for snapshots, and the related travis jazz, including encrypted credentials for sonatype.

### CODE REVIEW

**Comment by cgruber** [comment]
Note - this actually only occurs during a merge into master, so it can't really be tested until a pull request is merged.  It can be tested to ensure it doesn't break anything, but we'll only see it work if we see artifacts, adn inspect the output in the final merge.  It is thus precisely because we don't want 3 deployments per success (one for each jvm we test on)

**Comment by jrtom** [comment]
Looks plausible.  I'm still going to want to make sure that I understand the steps to go through when doing a release, but this looks like it should at least reduce their number.  :)

**Comment by cgruber** [comment]
This won't actually reduce release steps, this does a micro-non-signed release of the snapshot artifact.  It does the relatively easy and automatable part. Sorry.  But I'll both give you a release script and release instructions.

**Comment by jrtom** [comment]
I am totally fine with having a script + instructions.  If pressed, I'd be fine with a (presumed somewhat lengthier and more detailed) set of instructions with no script.  :)

**Pull request merged**
