### PR TITLE
Draw edge label

### PR DESCRIPTION
**Pull request by takanori-ugai**
Sample code is edu.uci.ics.jung.samples.PluggableRendererDemo.
Cheking show edge label button at the bottom, NULL Exception is caught.
java.graph.util.Context.getIndex requires non null graph and element.

### CODE REVIEW

**Comment by jrtom** [comment]
That BasicEdgeLabelRenderer null graph reference bug is...weird.  No idea where that came from (nor why it hasn't been reported previously).  Thanks for tracking that down!

**Comment by jrtom** [comment]
I'm not sure that we want to go with the specific changes you're proposing to GraphMLReader2.
Here's where I'm coming from: 
* Adding an `InputStream` constructor seems a bit odd, since GraphML files are text, not undifferentiated bytes.  Can you tell us a bit more about where this need comes from?  
Also, would it suffice to just change the existing constructor to take a `Reader` instead of a `FileReader` (which would allow you to specify the character encoding via `InputStreamReader`/`FileInputStream`, which I'm guessing might be what you really want)?  Note that internally `fileReader` is actually just a `Reader` anyway, so that wouldn't break anything.
* If we really did need to support an `InputStream` constructor, then there are a couple of architectural changes that I'd prefer to make:
  - The constructors should be able to share almost all their code.
  - The `init()` method should be more defensive in design: right now it will throw if both `inputStream` and `fileReader` are null.  (Ideally, in fact, perhaps at least that aspect of the initialization that `init()` does could be moved into the constructors so that we wouldn't need to have an if-else at all.)

**Comment by takanori-ugai** [comment]
Reader requires to specify the charset in its constructor otherwise its use system default charset.
When a program reads a XML file, the charset is specified in the XML. The charset is unknown for the program and the charset may be different from the system default. The charset of the XML might be UTF-8 or UTF-16 or another. XMLReader detects the charset from the XML data stream if an inputstream is passed.
I agree your idea about the code design.

**Comment by jrtom** [comment]
Ah, OK, being able to get the character encoding from the XML file makes sense, so I guess we do need to support passing an `InputStream` in.

If you could factor out the shared constructor code, and move the inputStream/fileReader-related code into that shared method (so that we don't need the either-or logic that init() currently has), then I'll take another look.

If you don't have time to do that, I'll get to it eventually.

**Comment by jrtom** [comment]
I'm accepting the change and have filed bug #61 to do the refactoring I talked about above.  Thanks!

**Pull request merged**
