### PR TITLE
Format Java source files in jung-algorithms/* with google-java-format (#86)

### PR DESCRIPTION
**Pull request by jbduncan**
This PR is the first of many towards resolving #86.

A summary of the changes applied can be found in the commit message.

@jrtom If this PR is too large for you to review, please let me know and I'll split it up. :)

### CODE REVIEW

**Comment by jrtom** [comment]
There are a couple of things about this PR as currently conceived.

First, active development is taking place on the common.graph branch.  I don't plan to release further versions of JUNG based on what's currently in master unless we have to; I'd prefer to focus on getting 3.0 out ASAP.

Second, the common.graph branch is currently undergoing widely-dispersed changes to finish using the Guava common.graph types everywhere, and I'd prefer to avoid other large-scale changes until that's done, just to make the merges easier.

**Comment by jbduncan** [comment]
Okay, that makes a degree of sense to me. Does that mean you'd rather I wait off on applying large-scale changes like this until 3.0 is out of the door?

**Comment by jrtom** [comment]
I don't intend to wait until 3.0 is out the door for this, just until the JUNG graph classes have been replaced with the common.graph ones.  That's probably 90% done at this point.  

And I do want to focus on the common.graph branch.

**Comment by jbduncan** [comment]
Okay. If I've understood you correctly, you want me to wait for the `common.graph` branch (which as you've explained is probably 90% done now) to get merged into `master` before going through this again, because of difficulties with merging highly differing branches, is that correct?

**Comment by jrtom** [comment]
Not quite.  I'm doing all the development for 3.0 on the common.graph branch (that is, I'm essentially treating it as the master for 3.0 development, and creating branches off that), and the current plan (although I could be persuaded otherwise) is that merging into the master branch will be basically the last thing that happens before releasing 3.0.

(The reason for this is basically in case I _do_ need to release another 2.x version for some reason before 3.0 can come out.)

What I am proposing is that we wait for the common.graph branch to no longer have any remaining references to the original JUNG graph types, and then do the formatting cleanup on the common.graph branch.

**Comment by jbduncan** [comment]
Alright, that makes sense to me!

I'm happy to wait until all the references to the original JUNG graph types are gone and Guava's `common.graph` types are fully adopted before submitting a new PR based off the common.graph branch. I'll close this PR in the meantime.

**Pull request closed without merging**
