### PR TITLE
solves #112

### PR DESCRIPTION
**Pull request by wumpz**
MinimumSpanningTree-related issues #112

### CODE REVIEW

**Comment by wumpz** [comment]
So this correlates directly with #83?

I am lost. #112 said at first MST should be undirected and the demo shows now a graph that looks more suitable.

**Comment by jrtom** [comment]
@wumpz Sorry, I may have overdone my explanation.  :P :)  Let me try to state it more simply.

*   `MinimumSpanningTree` should not construct a `CTree[Network]` object; it should just construct a `Network` (that is undirected).  This is because `CTree[Network]` is specifically directed.
*   Therefore, some of the changes that you proposed to make are not necessary; see my previous comment for details.

Hope that helps; please continue the conversation if I'm still being confusing.

**Comment by wumpz** [comment]
Hope that is the change you requested.

**Comment by jrtom** [comment]
Whoops, lost track of this thread.

I think the current state should work fine.  Thanks for taking care of this.  :)

**Pull request merged**
