### PR TITLE
jung-algorithms/pom.xml: removed apparently unnecessary org.junit.jupiter dependencies

### PR DESCRIPTION
**Pull request by jrtom**

### CODE REVIEW

**Comment by jbduncan** [comment]
LGTM, for I agree that those dependencies are unneeded. :+1:

**Comment by jrtom** [comment]
@jbduncan If you have a moment, I'd be curious to know what you think of the `maven-jar-plugin` dependencies in `jung-api/pom.xml` and `jung-samples/pom.xml`.  My attention was drawn to them because of the error messages below.

We can presumably add version information to those plugins, but it's been long enough since they were added that I'm not actually sure what the purpose of each of them is.

```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for net.sf.jung:jung-api:jar:3.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ net.sf.jung:jung-api:[unknown-version], /Users/joshua/IdeaProjects/jung/jung-api/pom.xml, line 42, column 15
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for net.sf.jung:jung-samples:jar:3.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ net.sf.jung:jung-samples:[unknown-version], /Users/joshua/IdeaProjects/jung/jung-samples/pom.xml, line 59, column 15
```

**Comment by jbduncan** [comment]
Hi @jrtom. I'm actually not familiar with what `maven-jar-plugin` does, but I'd be happy to research it when I next find time within the next few days!

If I find out what it does, I could then look into what version we should use, and how we should set it, if you'd like.

**Comment by jrtom** [comment]
The plugin is for building jars: https://maven.apache.org/plugins/maven-jar-plugin/

The question I have is more whether that's actually something we need to be doing in either of those specific cases.  A place to start might be to find the PR in which they were added; hopefully they will provide some context.

**Comment by jbduncan** [comment]
@jrtom I did a GitHub-based git blame search just now for `jung-api/pom.xml` (https://github.com/jrtom/jung/blame/master/jung-api/pom.xml), but sadly I can't tell why `maven-jar-plugin` was added to `jung-api`, because it was apparently put there before JUNG was imported from the SourceForge SVN repo, meaning that here on GitHub, the history for the addition of `maven-jar-plugin` has been lost.

However, I do see that @cgruber edited the POMs at some point...

@cgruber Do you happen to know why `maven-jar-plugin` was ever applied in the first place?

(I've not checked `jung-samples/pom.xml` yet. I will check it in a moment.)

**Comment by jbduncan** [comment]
(The GitHub blame search for `jung-samples/pom.xml` seems to tell the same story as with `jung-api/pom.xml` (https://github.com/jrtom/jung/blame/master/jung-samples/pom.xml).)

**Comment by jbduncan** [comment]
(Although, interestingly, @tomnelson did add at some point a main class entry to the jar for `jung-samples` which runs [`NodeImageShaperDemo`](https://github.com/jrtom/jung/blob/eed6692c547c06237a700ab67ec549695c8f7202/jung-samples/src/main/java/edu/uci/ics/jung/samples/NodeImageShaperDemo.java). Since it's not the only main class in the samples, I'd suggest removing it until we know we definitely need it. :smiley:)

**Comment by jrtom** [comment]
That item was already there in the samples pom.xml, Tom just renamed it when he renamed the class.

I agree that I don't see any particular reason to keep those around; we can always add them back (and if we do, add some comments about what they're for :) ).

**Pull request merged**
