### PR TITLE
Clean up poms, eliminating redundancies and organizing versions of deps via properties.

### PR DESCRIPTION
**Pull request by cgruber**
Remove redundant configuration, plugins, dependencies, and notably, a few duplicate pom files that lived in the java source root when they should be in the project/module root.

### CODE REVIEW

**Comment by jrtom** [comment]
cgruber@: ball is in your court to address the other comments above.  Thanks.

**Comment by cgruber** [comment]
Ok.  PTAL.

**Comment by jrtom** [comment]
OK.  I assume that the woodstox dependency is in there for the contributed GraphML parser, so it may well be needed at runtime.  Not sure why there aren't any source references to it.

**Comment by jrtom** [comment]
I'm going to go ahead and merge this because I think it's basically fine, but I'm filing an issue to make sure we get the woodstox dependency back in such that it will be available at runtime for the io package.

**Comment by cgruber** [comment]
That's easy - we remove <scope>test</scope>.  But that's the key question...  can a downstream dependent project do without it?  Is it optional?  Is there a test-project with which we can verify?

**Comment by jrtom** [comment]
I don't know of a test project.  However, we can ask Nathan Mittler, who's now at Google and who contributed this code, if he knows of anything.

**Comment by jrtom** [comment]
Removed the woodstox dependency in #29.

**Pull request merged**
