### PR TITLE
Remove `Pair`

### LINKED ISSUE #110: Retire `Pair` type
Now that the JUNG graph types are gone, it's only used (internally) by the `StructurallyEquivalent` class.  At the least we don't need a public type for this, and we probably don't need something that is basically an ImmutableList anyway.

### PR DESCRIPTION
**Pull request by jbduncan**
Fixes #110.

### CODE REVIEW

**Comment by jrtom** [comment]
Thanks!

**Comment by jbduncan** [comment]
@tomnelson Oh very sorry, I hadn't realised that my change in jung-visualization would cause you merge conflicts. I'd be more than happy to leave jung-visualization alone from now on until your work on it has been merged.

(I'd be envious to work with better tools than Git! I only recently graduated in Computer Science two to three months ago, and I'm still looking for a full-time job, so I guess that my lack of good-Git-citizen awareness comes from my lack of experience. :stuck_out_tongue:)

**Comment by tomnelson** [comment]
No problem, and I hope that was helpful and not condescending. 
I'm going to hold off on any contributions to JUNG until the project is more active. I've invested maybe 200 hours refactoring and fixing the viz code that I originally designed and wrote, but the project is not active enough for me to continue work with at this time. 
Thanks for your efforts in combing my code for style improvements and getting me to look harder at Java8. Some of us are still working on very large projects that have not moved to java8 so we tend to be late to the party!

**Comment by jrtom** [comment]
That's partially my fault; I simply completely failed to notice that the "remove Pair" PR was also touching code in a completely different part of the code base (and, in particular, one of the demos that you were also touching).

I make more use of Git now than I used to, in part because my team at work is responsible for a different GitHub-based project ([Kythe](https://github.com/google/kythe)).  And yes, when we're doing work in that domain then we do miss the internal tools that we have.  :/

@tomnelson, I will continue to comment on PR #140; I'm pretty sure we're going to want to land that change, to get us into a better state than the one we're in right now.  I don't know how convenient it would be for you to resurrect that branch and PR, but I hope you'll be able to help us out once I've finished going over it.

**Pull request merged**
